context:
  name: vsg
  version: "3.30.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/jeremiah-c-leary/vhdl-style-guide/archive/refs/tags/${{ version }}.tar.gz
  sha256: cd394fa6feebe7aa704a41aed9c743baf701d60807f73d191717dcfa188d240c

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - vsg = vsg.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-git-versioning
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - pyyaml >=5.1

tests:
  - python:
      imports:
        - vsg
  - script:
      - vsg --help
      - pytest --no-cov
    files:
      source:
        - bin/
        - docs/
        - vsg/
        - tests/
        - pyproject.toml
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip
        - pytest
        - pytest-cov
        - pytest-html
        - pytest-xdist

about:
  summary: Coding style enforcement for VHDL
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/jeremiah-c-leary/vhdl-style-guide
  documentation: https://vhdl-style-guide.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - blmaier
